(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={items:[],paper:null,pdf:null,page:1,scale:1.2,tool:'select',annotations:[],categories:[],renderToken:0,pending:null,undo:[]};
async function api(url,opts={}){const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||r.status);return d}
async function ensurePdfJs(){
 if(window.pdfjsLib)return;
 await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)});
 if(!window.pdfjsLib) throw new Error('PDF.js 加载失败，请检查网络。'); window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
}
function statusBadge(s){return '<span class="lit-status '+(s==='已读'?'done':s==='在读'?'reading':'')+'">'+esc(s||'未读')+'</span>'}
function itemHtml(x){return '<article class="lit-item '+(S.paper?.id===x.id?'active':'')+'" data-lit-id="'+x.id+'"><div class="lit-item-title">'+esc(x.title)+'</div><div class="lit-item-meta">'+esc(x.authors||'')+(x.year?' · '+esc(x.year):'')+'</div><div class="lit-item-foot">'+statusBadge(x.reading_status)+(x.categories||[]).slice(0,2).map(c=>'<span class="lit-chip">'+esc(c)+'</span>').join('')+(x.favorite?'<span title="收藏">★</span>':'')+'</div></article>'}
async function loadList(){
 const q=$('#lit-search')?.value||'', st=$('#lit-status')?.value||'', cat=$('#lit-category')?.value||'';
 const d=await api('/api/literature?q='+encodeURIComponent(q)+'&status='+encodeURIComponent(st)+'&category='+encodeURIComponent(cat)+'&page_size=100');
 S.items=d.items||[]; S.categories=[...new Set(S.items.flatMap(x=>x.categories||[]))].sort();
 const list=$('#lit-list');if(list)list.innerHTML=S.items.length?S.items.map(itemHtml).join(''):'<div class="lit-empty">暂无文献<br>点击“上传 PDF”开始</div>';
 const sel=$('#lit-category');if(sel){const v=sel.value;sel.innerHTML='<option value="">全部分类</option>'+S.categories.map(x=>'<option '+(x===v?'selected':'')+'>'+esc(x)+'</option>').join('')}
 $('[data-lit-id]').forEach(x=>x.onclick=()=>openPaper(x.dataset.litId));
}
function shell(){
 const main=$('#main');if(!main)return;
 main.innerHTML='<div class="lit-shell"><aside class="card lit-library"><div class="lit-library-head"><div><div class="card-kicker">LITERATURE LIBRARY</div><h3>文献库</h3></div><button class="primary-btn" id="lit-upload">＋ 上传 PDF</button></div><input id="lit-file" type="file" accept="application/pdf,.pdf" hidden><input class="search-input" id="lit-search" placeholder="搜索题名、作者、标签、分类…"><div class="lit-filters"><select class="search-input" id="lit-status"><option value="">全部进度</option><option>未读</option><option>在读</option><option>已读</option></select><select class="search-input" id="lit-category"><option value="">全部分类</option></select></div><div class="lit-list" id="lit-list"></div></aside><section class="card lit-reader"><div id="lit-reader-empty" class="lit-empty lit-reader-empty">选择一篇文献开始阅读</div><div id="lit-reader-live" hidden><div class="lit-toolbar"><button data-lit-tool="select" class="active">选择</button><button data-lit-tool="highlight">高亮</button><button data-lit-tool="underline">下划线</button><button data-lit-tool="strikeout">删除线</button><button data-lit-tool="rect">框选</button><button data-lit-tool="ink">画笔</button><span class="lit-sep"></span><button id="lit-prev">‹</button><span id="lit-page-label">1 / 1</span><button id="lit-next">›</button><button id="lit-zoom-out">−</button><span id="lit-zoom-label">120%</span><button id="lit-zoom-in">＋</button></div><div class="lit-canvas-scroll" id="lit-scroll"><div class="lit-page" id="lit-page"><canvas id="lit-canvas"></canvas><div id="lit-text-layer" class="lit-text-layer"></div><svg id="lit-annotation-layer" class="lit-annotation-layer"></svg></div></div></div></section><aside class="card lit-side" id="lit-side"><div class="lit-empty">文献信息、批注和笔记将在这里显示</div></aside></div>';
 $('#lit-upload').onclick=()=>$('#lit-file').click(); $('#lit-file').onchange=e=>upload(e.target.files?.[0]);
 let t;$('#lit-search').oninput=()=>{clearTimeout(t);t=setTimeout(loadList,160)};$('#lit-status').onchange=loadList;$('#lit-category').onchange=loadList;
}
async function upload(file){if(!file)return;try{const r=await fetch('/api/literature/import',{method:'POST',headers:{'Content-Type':'application/pdf','X-Filename':encodeURIComponent(file.name)},body:file});if(!r.ok)throw new Error((await r.json()).message||'上传失败');const x=await r.json();await loadList();await openPaper(x.id)}catch(e){alert(e.message)}finally{$('#lit-file').value=''}}
async function openPaper(id){
 S.paper=await api('/api/literature/'+encodeURIComponent(id));S.page=Math.max(1,+S.paper.last_page||1);S.pdf=null;
 $('#lit-reader-empty').hidden=true;$('#lit-reader-live').hidden=false; renderSide(); await loadList();
 try{await ensurePdfJs();S.pdf=await window.pdfjsLib.getDocument({url:'/api/literature/'+encodeURIComponent(id)+'/pdf',rangeChunkSize:4*1024*1024}).promise;S.paper.page_count=S.pdf.numPages;S.page=Math.min(S.page,S.pdf.numPages);await renderPage()}catch(e){$('#lit-page').innerHTML='<div class="lit-empty">PDF 渲染器加载失败：'+esc(e.message)+'</div>'}
}
async function renderPage(){
 if(!S.pdf)return;const token=++S.renderToken,page=await S.pdf.getPage(S.page),vp=page.getViewport({scale:S.scale});
 const canvas=$('#lit-canvas'),ctx=canvas.getContext('2d'),ratio=window.devicePixelRatio||1;canvas.width=Math.floor(vp.width*ratio);canvas.height=Math.floor(vp.height*ratio);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';$('#lit-page').style.width=vp.width+'px';$('#lit-page').style.height=vp.height+'px';
 await page.render({canvasContext:ctx,viewport:vp,transform:ratio===1?null:[ratio,0,0,ratio,0,0]}).promise;if(token!==S.renderToken)return;
 const text=await page.getTextContent(),layer=$('#lit-text-layer');layer.innerHTML='';layer.style.width=vp.width+'px';layer.style.height=vp.height+'px';
 text.items.forEach(it=>{const tx=window.pdfjsLib.Util.transform(vp.transform,it.transform),span=document.createElement('span');span.textContent=it.str;span.style.left=tx[4]+'px';span.style.top=(tx[5]-Math.abs(tx[3]))+'px';span.style.fontSize=Math.abs(tx[3])+'px';span.style.transform='scaleX('+(it.width*S.scale/Math.max(1,span.textContent.length*Math.abs(tx[3])*.5))+')';layer.appendChild(span)});
 S.annotations=await api('/api/literature/'+S.paper.id+'/annotations?page='+S.page);paintAnnotations();
 $('#lit-page-label').textContent=S.page+' / '+S.pdf.numPages;$('#lit-zoom-label').textContent=Math.round(S.scale*100)+'%';
 api('/api/literature/'+S.paper.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({last_page:S.page,page_count:S.pdf.numPages,reading_status:S.paper.reading_status==='未读'?'在读':S.paper.reading_status})}).catch(()=>{});
 renderAnnotationList(); wireSelection();
}
function paintAnnotations(){const svg=$('#lit-annotation-layer');svg.innerHTML='';svg.setAttribute('viewBox','0 0 1 1');for(const a of S.annotations){for(const r of a.rects||[]){const e=document.createElementNS('http://www.w3.org/2000/svg','rect');e.setAttribute('x',r[0]);e.setAttribute('y',r[1]);e.setAttribute('width',r[2]-r[0]);e.setAttribute('height',r[3]-r[1]);e.setAttribute('class','ann-'+a.type);svg.appendChild(e)}if((a.points||[]).length>1){const p=document.createElementNS('http://www.w3.org/2000/svg','polyline');p.setAttribute('points',a.points.map(x=>x[0]+','+x[1]).join(' '));p.setAttribute('class','ann-ink');svg.appendChild(p)}}}
function wireSelection(){const layer=$('#lit-text-layer'),svg=$('#lit-annotation-layer'),page=$('#lit-page');
 svg.style.pointerEvents=['rect','ink'].includes(S.tool)?'auto':'none';
 let drawing=null;
 svg.onpointerdown=e=>{if(!['rect','ink'].includes(S.tool))return;e.preventDefault();const r=page.getBoundingClientRect(),p=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];drawing={start:p,points:[p]};svg.setPointerCapture?.(e.pointerId)};
 svg.onpointermove=e=>{if(!drawing||S.tool!=='ink')return;const r=page.getBoundingClientRect();drawing.points.push([(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height])};
 svg.onpointerup=async e=>{if(!drawing)return;const r=page.getBoundingClientRect(),end=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height],d=drawing;drawing=null;let body={page:S.page,type:S.tool,comment:prompt('批注笔记（可留空）','')??''};if(S.tool==='rect')body.rects=[[Math.min(d.start[0],end[0]),Math.min(d.start[1],end[1]),Math.max(d.start[0],end[0]),Math.max(d.start[1],end[1])]];else body.points=d.points.concat([end]);await api('/api/literature/'+S.paper.id+'/annotations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await renderPage()};
layer.onmouseup=()=>{const sel=window.getSelection();if(!sel||sel.isCollapsed)return;const range=sel.getRangeAt(0),page=$('#lit-page'),pr=page.getBoundingClientRect();const rects=[...range.getClientRects()].filter(r=>r.width>1&&r.height>1).map(r=>[(r.left-pr.left)/pr.width,(r.top-pr.top)/pr.height,(r.right-pr.left)/pr.width,(r.bottom-pr.top)/pr.height]);if(!rects.length)return;S.pending={page:S.page,rects,text:sel.toString()};sel.removeAllRanges();paintPendingSelection();$$('[data-lit-tool]').forEach(b=>b.classList.toggle('ready',['highlight','underline','strikeout'].includes(b.dataset.litTool)))}}
function paintPendingSelection(){let old=$('#lit-pending-layer');old?.remove();if(!S.pending)return;const page=$('#lit-page'),d=document.createElement('div');d.id='lit-pending-layer';d.className='lit-pending-layer';for(const r of S.pending.rects){const x=document.createElement('i');x.style.cssText='left:'+(r[0]*100)+'%;top:'+(r[1]*100)+'%;width:'+((r[2]-r[0])*100)+'%;height:'+((r[3]-r[1])*100)+'%';d.appendChild(x)}page.appendChild(d)}
async function commitPending(type){if(!S.pending)return;const comment=prompt('批注笔记（可留空）','');if(comment===null)return;const row=await api('/api/literature/'+S.paper.id+'/annotations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...S.pending,type,comment})});S.undo.push({id:row.id,page:S.pending.page});S.pending=null;$('#lit-pending-layer')?.remove();$$('[data-lit-tool]').forEach(b=>b.classList.remove('ready'));await renderPage()}
async function undoAnnotation(){const x=S.undo.pop();if(!x)return;await api('/api/literature/'+S.paper.id+'/annotations/'+x.id,{method:'DELETE'});await renderPage()}
function renderSide(){const p=S.paper;if(!p)return;$('#lit-side').innerHTML='<div class="lit-side-tabs"><button class="active" data-lit-tab="info">信息</button><button data-lit-tab="annotations">批注</button><button data-lit-tab="notes">笔记</button></div><div id="lit-side-body"></div>';$('[data-lit-tab]').forEach(b=>b.onclick=()=>{$('[data-lit-tab]').forEach(x=>x.classList.toggle('active',x===b));renderSideTab(b.dataset.litTab)});renderSideTab('info')}
function renderSideTab(tab){const root=$('#lit-side-body'),p=S.paper;if(tab==='info'){root.innerHTML='<div class="lit-info"><label>题名<input id="li-title" value="'+esc(p.title)+'"></label><label>作者<input id="li-authors" value="'+esc(p.authors||'')+'"></label><div class="lit-two"><label>年份<input id="li-year" value="'+esc(p.year||'')+'"></label><label>阅读状态<select id="li-status"><option '+(p.reading_status==='未读'?'selected':'')+'>未读</option><option '+(p.reading_status==='在读'?'selected':'')+'>在读</option><option '+(p.reading_status==='已读'?'selected':'')+'>已读</option></select></label></div><label>分类（逗号分隔）<input id="li-categories" value="'+esc((p.categories||[]).join(', '))+'"></label><label>标签（逗号分隔）<input id="li-tags" value="'+esc((p.tags||[]).join(', '))+'"></label><label>期刊 / 会议<input id="li-venue" value="'+esc(p.venue||'')+'"></label><div class="lit-two"><label>DOI<input id="li-doi" value="'+esc(p.doi||'')+'"></label><label>Cite Key<input id="li-cite" value="'+esc(p.cite_key||'')+'"></label></div><label class="lit-favorite"><input type="checkbox" id="li-favorite" '+(p.favorite?'checked':'')+'> 收藏此文献</label><button class="primary-btn" id="li-save">保存信息</button></div>';$('#li-save').onclick=saveInfo}else if(tab==='annotations')renderAnnotationList();else loadNote()}
async function saveInfo(){const patch={title:$('#li-title').value,authors:$('#li-authors').value,year:$('#li-year').value,reading_status:$('#li-status').value,categories:$('#li-categories').value.split(',').map(x=>x.trim()).filter(Boolean),tags:$('#li-tags').value.split(',').map(x=>x.trim()).filter(Boolean),venue:$('#li-venue').value,doi:$('#li-doi').value,cite_key:$('#li-cite').value,favorite:$('#li-favorite').checked};S.paper=await api('/api/literature/'+S.paper.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});await loadList()}
function renderAnnotationList(){const root=$('#lit-side-body');if(!root||!$('[data-lit-tab="annotations"]')?.classList.contains('active'))return;root.innerHTML='<div class="lit-ann-list">'+(S.annotations.length?S.annotations.map(a=>'<article class="lit-ann"><div><strong>P.'+a.page+' · '+esc(a.type)+'</strong><button data-ann-del="'+a.id+'">×</button></div><blockquote>'+esc(a.text||'区域批注')+'</blockquote>'+(a.comment?'<p>'+esc(a.comment)+'</p>':'')+'</article>').join(''):'<div class="lit-empty">当前页暂无批注</div>')+'</div>';$('[data-ann-del]').forEach(b=>b.onclick=async()=>{await api('/api/literature/'+S.paper.id+'/annotations/'+b.dataset.annDel,{method:'DELETE'});await renderPage()})}
async function loadNote(){const root=$('#lit-side-body'),d=await api('/api/literature/'+S.paper.id+'/note');root.innerHTML='<textarea class="lit-note" id="lit-note" placeholder="Markdown 文献笔记…">'+esc(d.content||'')+'</textarea><div class="lit-note-actions"><span>Markdown · Ctrl+S 保存</span><button class="primary-btn" id="lit-note-save">保存笔记</button></div>';$('#lit-note-save').onclick=saveNote}
async function saveNote(){await api('/api/literature/'+S.paper.id+'/note',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:$('#lit-note').value})})}
function bindReader(){
 $$('[data-lit-tool]').forEach(b=>b.onclick=()=>{S.tool=b.dataset.litTool;$$('[data-lit-tool]').forEach(x=>x.classList.toggle('active',x===b));wireSelection()});
 $('#lit-prev').onclick=()=>{if(S.page>1){S.page--;renderPage()}};$('#lit-next').onclick=()=>{if(S.pdf&&S.page<S.pdf.numPages){S.page++;renderPage()}};let wheelLock=false;$('#lit-scroll').onwheel=e=>{if(!S.pdf||e.ctrlKey)return;e.preventDefault();if(wheelLock)return;wheelLock=true;setTimeout(()=>wheelLock=false,120);if(e.deltaY>0&&S.page<S.pdf.numPages){S.page++;renderPage()}else if(e.deltaY<0&&S.page>1){S.page--;renderPage()}};
 $('#lit-zoom-in').onclick=()=>{S.scale=Math.min(2.5,S.scale+.15);renderPage()};$('#lit-zoom-out').onclick=()=>{S.scale=Math.max(.6,S.scale-.15);renderPage()};
}
async function start(){shell();bindReader();await loadList()}
window.ERWLiterature={start};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&$('#lit-note')){e.preventDefault();saveNote()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&S.paper){e.preventDefault();undoAnnotation()}});
})();